name: Push actions

on: push

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          . install_poetry.sh
          poetry install
      - name: Format code
        run: |
          poetry run pre-commit run -a
      - name: Run tests
        run: |
          poetry run pytest
  deploy:
    runs-on: ubuntu-latest
    needs: default
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Deploy to PyPi
        run: |
          . install_poetry.sh
          poetry publish --build -u ${{ secrets.PYPI_USERNAME}} -p ${{ secrets.PYPI_PASSWORD }}